### ISSUE TITLE
migration error due to props on m2m fields 

### ISSUE THREAD

**Issue by mcclory** [IntrospectData/django-kubernetes-manager#19]
**Describe the bug**
When performing migrations on a project that consumes this one, it pops the following non-breaking warnings: 

```
kubernetes_manager.KubernetesContainer.volume_mounts: (fields.W340) null has no effect on ManyToManyField.
kubernetes_manager.KubernetesPodTemplate.volumes: (fields.W340) null has no effect on ManyToManyField.
```
**To Reproduce**
1. start a new project, install and register this app to the project 
2. run `migrate`

**Expected behavior**

Shouldn't see warnings for this project

**Screenshots**

![image](https://user-images.githubusercontent.com/22857655/80316627-ae37a700-87b3-11ea-9c09-b134405ef712.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: leviathan
- OS: Pop 20.04 beta

**Comment by breimers** [comment]
Fixed.
