### ISSUE TITLE
Fix "file_lines" issue in django_kubernetes_manager/models/base.py

### ISSUE THREAD

**Issue by breimers** [IntrospectData/django-kubernetes-manager#4]
File `base.py` has 477 lines of code (exceeds 250 allowed). Consider refactoring.

https://codeclimate.com/github/IntrospectData/django-kubernetes-manager/django_kubernetes_manager/models/base.py#issue_5e86db81132991000100003e

**Comment by mcclory** [comment]
Slapped down extra line issues and handled length/formatting validation: 

* added support for black (code formatting) and formatting rules 
* added support for isort (imports management) and rules 
* added flake8 config 
* added codeclimate yaml config for tweaking analysis results if/when we want to accept higher levels of complexity, ect.
